#! /bin/sh
nitrogen --restore
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

DEFAULT_NETWORK_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

~/.config/polybar/launch.sh
# killall compton
killall dunst
dunst&
# compton&

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color '#a971f6'
bspc config focused_border_color '#2196F3'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Lazarus state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^10' follow=off

xsetroot -cursor_name left_ptr
